# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "maria-s-tfstate-s3-bucket"
    dynamodb_table = "maria-s-tfstate-s3-bucket-lock"
    encrypt        = true
    key            = "backend/terraform.tfstate"
    region         = "us-east-1"
  }
}
