name: "Terraform"
on: 
  push: 
    branches: 
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  working_directory: task_2
  tf_version: 'latest'
  tg_version: 'latest'

defaults:
  run:
    working-directory: task_2

jobs:
  terraform-init:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Terragrunt init
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_directory }}
          tg_command: 'init'

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-init
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terragrunt init
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_directory }}
          tg_command: 'init'
      - name: Terraform fmt
        run: terraform fmt -check
      - name: Terraform plan
        run: terraform plan

  terraform-apply:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: terraform-plan
    permissions:
      id-token: write  
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
          aws-region: ${{ vars.AWS_REGION }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Terragrunt init
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_directory }}
          tg_command: 'init'
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform apply
        run: terraform apply -auto-approve